Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : igor de jesus silva
// Data atual  : 20/03/2021
Var
// Seção de Declarações das variáveis 
a, b, c:inteiro
Inicio
//entrda
escreval("digite um valor")
leia(a)
escreval("digite o segundo valor")
leia(b)
//processamento
c <- a

a<-b
b<-c
//saida
escreval("TROCA")
escreval("valor de A ficou", a)
escreval("valor de B ficou", b)

Fimalgoritmo